name = "blockzone-api"
main = "./worker/tournament-manager.js"
compatibility_date = "2023-12-01"

[[kv_namespaces]]
binding = "PLAYERS"
id = "afdca5fda8b343b99541432574cfa5c3"

[[kv_namespaces]]
binding = "SCORES"
id = "8e4d3de3c359495186eabf9032d08d8f"

[[kv_namespaces]]
binding = "TOURNAMENTS"
id = "d4f40a571cdc49a98d5dd1d9f3a983ea"

[[kv_namespaces]]
binding = "SESSIONS"
id = "9472d4328eda428090494844a4cdba9b"

[[kv_namespaces]]
binding = "REWARDS"
id = "66d8e0a1ead24a9c916bd22551cf1515"